name: climbapp
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  bloc: ^8.1.2
  cloud_firestore: ^4.13.2
  connectivity_plus: ^5.0.2
  dartz: ^0.10.1
  equatable: ^2.0.5
  firebase_auth: ^4.14.1
  firebase_core: ^2.23.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  fluttertoast: ^8.2.4
  get_it: ^7.6.4
  google_sign_in: ^6.2.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^1.1.0
  intl: ^0.18.0
  json_annotation: ^4.8.1
  path_provider: ^2.1.1

dev_dependencies:
  bloc_test: ^9.1.4
  build_runner: ^2.4.7
  flutter_test:
    sdk: flutter
  freezed: ^2.4.5
  hive_generator: ^2.0.1
  json_serializable: ^6.7.1
  mockito: ^5.4.3
  mocktail: ^1.0.0
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  generate: true
